[workspace]

members = [
    "logpack",
    "logpack-derive",
    "logpack-ron",
    "test",
    "test/hexdump",
]

[patch.crates-io]
logpack = { path = "logpack" }
logpack-derive = { path = "logpack-derive" }
logpack-ron = { path = "logpack-ron" }
hexdump = { path = "test/hexdump" }
