[package]
name = "logpack-derive"
version = "0.2.0"
authors = ["Dan Aloni <alonid@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.*"
quote = "1.*"
syn = { version = "1.*", features = ["extra-traits", "full"]  }
