[package]
name = "logpack"
version = "0.2.0"
authors = ["Dan Aloni <alonid@gmail.com>"]
edition = "2018"

[dependencies]
serde = "^1.0.27"
serde_derive = "^1.0.27"
bytes = "0.*"
libc = "*"
cfg-if = "0.1"

[dev-dependencies]
ron = "*"
